### ISSUE TITLE
Unable to use resurant service code more than once

### ISSUE THREAD

**Issue by Barnesey41** [tomii-ssb/kashyyyk-hotel-booking#5]
unable to book a table after having done so once already despite more than one party being checked in.

![wont let me book a table](https://user-images.githubusercontent.com/74460619/99280605-6ea4db00-2829-11eb-9767-21d6608284ac.PNG)

**Comment by tomii-ssb** [comment]
fixed, while loop in book_table() was running on the condition of q == 0, which was a global variable

q was updated within the loop to be > 0, meaning that next time the function was called the condition wasn't true, and the loop didn't run

fix: declared q within the scope of the function, rather than having it be global 👍
